apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hello-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/JunTu-XD/node-hello
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/manifests
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: hello-app
  namespace: flux-system
spec:
  interval: 5m0s
  path: "./manifests"
  prune: true
  sourceRef:
    kind: GitRepository
    name: hello-app
  targetNamespace: app